"""Generate test DOCX files for the anonymizer tool."""

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "test_docs"
OUTPUT_DIR.mkdir(exist_ok=True)

def create_simple_letter():
    """Create a simple business letter with names and contact info."""
    doc = Document()
    
    doc.add_heading("Business Letter", 0)
    
    doc.add_paragraph("From: John Smith")
    doc.add_paragraph("Email: john.smith@acmecorp.com")
    doc.add_paragraph("Phone: 555-123-4567")
    doc.add_paragraph("")
    
    doc.add_paragraph("To: Sarah Johnson")
    doc.add_paragraph("Email: sarah.johnson@techstart.io")
    doc.add_paragraph("")
    
    doc.add_paragraph("Dear Sarah Johnson,")
    doc.add_paragraph(
        "I am writing to confirm the partnership between Acme Corporation and TechStart Inc. "
        "As discussed with your CEO, Michael Brown, we will proceed with the $50,000 investment "
        "by end of Q1."
    )
    doc.add_paragraph(
        "Please contact John Smith at 555-123-4567 if you have any questions. "
        "Our CFO, Emily Davis, will handle the financial arrangements totaling €75,000."
    )
    doc.add_paragraph("")
    doc.add_paragraph("Best regards,")
    doc.add_paragraph("John Smith")
    doc.add_paragraph("CEO, Acme Corporation")
    
    doc.save(OUTPUT_DIR / "01_simple_letter.docx")
    print("Created: 01_simple_letter.docx")


def create_financial_report():
    """Create a document with lots of financial data."""
    doc = Document()
    
    doc.add_heading("Q4 2025 Financial Report", 0)
    doc.add_heading("Prepared by: Finance Team - Robert Chen", level=1)
    
    doc.add_paragraph(
        "This report summarizes the financial performance for TechGlobal Inc. "
        "under the leadership of CEO Amanda White."
    )
    
    doc.add_heading("Revenue Summary", level=2)
    
    # Add a table with financial data
    table = doc.add_table(rows=5, cols=3)
    table.style = "Table Grid"
    
    headers = table.rows[0].cells
    headers[0].text = "Category"
    headers[1].text = "Amount"
    headers[2].text = "Manager"
    
    data = [
        ("Product Sales", "$1,234,567.89", "James Wilson"),
        ("Services", "€456,789.00", "Lisa Anderson"),
        ("Licensing", "£89,000.50", "David Thompson"),
        ("Consulting", "$234,567.00", "Jennifer Martinez"),
    ]
    
    for i, (cat, amt, mgr) in enumerate(data, 1):
        row = table.rows[i].cells
        row[0].text = cat
        row[1].text = amt
        row[2].text = mgr
    
    doc.add_paragraph("")
    doc.add_paragraph(
        "Total revenue: $2,014,924.39. Contact Robert Chen at robert.chen@techglobal.com "
        "or 555-987-6543 for details."
    )
    
    doc.save(OUTPUT_DIR / "02_financial_report.docx")
    print("Created: 02_financial_report.docx")


def create_employee_directory():
    """Create a document with employee information in a table."""
    doc = Document()
    
    doc.add_heading("Employee Directory - Confidential", 0)
    doc.add_paragraph("Sunset Technologies Ltd.")
    
    table = doc.add_table(rows=6, cols=4)
    table.style = "Table Grid"
    
    headers = table.rows[0].cells
    headers[0].text = "Name"
    headers[1].text = "Email"
    headers[2].text = "Phone"
    headers[3].text = "Salary"
    
    employees = [
        ("Alice Cooper", "alice.cooper@sunset.tech", "555-111-2222", "$85,000"),
        ("Bob Williams", "bob.williams@sunset.tech", "555-333-4444", "$92,500"),
        ("Carol Martinez", "carol.martinez@sunset.tech", "555-555-6666", "€78,000"),
        ("Daniel Kim", "daniel.kim@sunset.tech", "555-777-8888", "£65,000"),
        ("Eva Schmidt", "eva.schmidt@sunset.tech", "555-999-0000", "$105,000"),
    ]
    
    for i, (name, email, phone, salary) in enumerate(employees, 1):
        row = table.rows[i].cells
        row[0].text = name
        row[1].text = email
        row[2].text = phone
        row[3].text = salary
    
    doc.add_paragraph("")
    doc.add_paragraph("Report generated by HR Manager: Patricia Young (patricia.young@sunset.tech)")
    
    doc.save(OUTPUT_DIR / "03_employee_directory.docx")
    print("Created: 03_employee_directory.docx")


def create_contract():
    """Create a contract-style document."""
    doc = Document()
    
    doc.add_heading("SERVICE AGREEMENT", 0)
    
    doc.add_paragraph(
        "This Service Agreement (\"Agreement\") is entered into as of January 1, 2026, "
        "by and between:"
    )
    
    doc.add_paragraph(
        "PARTY A: GlobalServices Corp., represented by Thomas Anderson "
        "(thomas.anderson@globalservices.com, Phone: 555-ABC-1234)"
    )
    
    doc.add_paragraph(
        "PARTY B: Innovation Labs LLC, represented by Maria Garcia "
        "(maria.garcia@innovationlabs.io, Phone: 555-XYZ-5678)"
    )
    
    doc.add_heading("Terms and Conditions", level=1)
    
    doc.add_paragraph(
        "1. GlobalServices Corp. agrees to provide consulting services to Innovation Labs LLC "
        "for a total fee of $150,000.00 (one hundred fifty thousand dollars)."
    )
    
    doc.add_paragraph(
        "2. Payment shall be made in three installments: $50,000 on signing, "
        "€45,000 at midpoint, and £40,000 upon completion."
    )
    
    doc.add_paragraph(
        "3. Primary contact for GlobalServices Corp.: Thomas Anderson\n"
        "   Secondary contact: Rebecca Lee (rebecca.lee@globalservices.com)"
    )
    
    doc.add_paragraph("")
    doc.add_paragraph("_________________________")
    doc.add_paragraph("Thomas Anderson, CEO")
    doc.add_paragraph("GlobalServices Corp.")
    
    doc.add_paragraph("")
    doc.add_paragraph("_________________________")
    doc.add_paragraph("Maria Garcia, President")
    doc.add_paragraph("Innovation Labs LLC")
    
    doc.save(OUTPUT_DIR / "04_service_contract.docx")
    print("Created: 04_service_contract.docx")


def create_nested_tables():
    """Create a document with nested tables to test recursive processing."""
    doc = Document()
    
    doc.add_heading("Project Status Report", 0)
    doc.add_paragraph("Project Manager: Chris Evans (chris.evans@projects.com)")
    
    # Outer table
    outer_table = doc.add_table(rows=2, cols=2)
    outer_table.style = "Table Grid"
    
    outer_table.rows[0].cells[0].text = "Project Alpha - Lead: Nancy Drew"
    outer_table.rows[0].cells[1].text = "Budget: $500,000"
    
    # Nested table in second row
    cell = outer_table.rows[1].cells[0]
    cell.text = "Team Members:"
    
    nested_table = cell.add_table(rows=3, cols=2)
    nested_table.style = "Table Grid"
    nested_table.rows[0].cells[0].text = "Steve Rogers"
    nested_table.rows[0].cells[1].text = "steve@team.com"
    nested_table.rows[1].cells[0].text = "Tony Stark"
    nested_table.rows[1].cells[1].text = "tony@team.com"
    nested_table.rows[2].cells[0].text = "Bruce Banner"
    nested_table.rows[2].cells[1].text = "bruce@team.com"
    
    outer_table.rows[1].cells[1].text = "Remaining: €250,000"
    
    doc.save(OUTPUT_DIR / "05_nested_tables.docx")
    print("Created: 05_nested_tables.docx")


if __name__ == "__main__":
    print("Generating test documents...")
    create_simple_letter()
    create_financial_report()
    create_employee_directory()
    create_contract()
    create_nested_tables()
    print(f"\nAll test documents saved to: {OUTPUT_DIR}")
